spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydb


security:
  header.name: Authorization
  token.secret: changeit

#server:
#  port: 8888

logging:
  level:
    ROOT: INFO
    com.anjey: DEBUG
